<?php

/**
 * AUTO-GENERATED by synthigy-codegen from movies.xsql — DO NOT EDIT.
 * sourceHash: bd29e96765e3f732946b8fd00104834ab586e7bc2951a2cb10a316e80f64c93d
 * Regenerate: bin/synthigy-codegen gen movies.xsql
 *
 * Data keys are snake_case verbatim — server-native, no casing transform.
 */

declare(strict_types=1);

namespace Generated;

const _SRC_MOVIE_LIST = '@search list
movie (release_year > ?since:int=1980, limit ?limit:int=20, offset ?offset:int=0, order by release_year desc)
  xid
  title (ilike ?q:string="%")
  release_year
  _count
    ratings:movie_ratings
    actors:actors
  _agg
    ratings:movie_ratings
      value: avg
  ->genres
    xid
    name';
const _SRC_MOVIE_DETAIL = '@get detail
movie (xid = ?xid:string)
  xid
  title
  release_year
  ->movie_ratings
    xid
    value
    review
    ->created_by
      xid
      name
  ->genres
    xid
    name
  ->actors
    xid
    name
    birth_year';
const _SRC_MOVIE_COUNT = 'SELECT count(*) AS total FROM {movie}
WHERE release_year > ?since:int=1995 AND title ILIKE ?q:string="%"';
const _SRC_DASHBOARD_STATS = '-- One CTE per entity, not scalar subqueries: RLS guards are injected per
-- CTE scope, so each aggregate is scoped to what the caller may read.
WITH m  AS (SELECT count(*) AS n FROM {movie}),
     r  AS (SELECT count(*) AS n, avg({user_rating.value}) AS avg_value FROM {user_rating}),
     ma AS (SELECT count(*) AS n FROM {movie_actor})
SELECT m.n          AS total_movies,
       r.n          AS total_ratings,
       r.avg_value  AS avg_rating,
       ma.n         AS total_actors
FROM m, r, ma';

/** Typed operations for XSQL namespace 'dashboard'. */
final class Dashboard
{
    /**
     * @return list<array{total_movies: int, total_ratings: int, avg_rating: float|null, total_actors: int}>
     */
    public static function stats(?string $actingAs = null): array
    {
        $data = \Synthigy\Synthigy::sqlTemplate(_SRC_DASHBOARD_STATS, [], actingAs: $actingAs);
        return is_array($data) ? array_values($data) : [];
    }
}

/** Typed operations for XSQL namespace 'movie'. */
final class Movie
{
    /**
     * @param array{since?: int, limit?: int, offset?: int, q?: string} $params
     * @return list<array{xid: string, title: string|null, release_year: int|null, _count?: array<string, int>, _agg?: array<string, mixed>, genres?: list<array{xid: string, name: string|null}>}>
     */
    public static function list(array $params = [], ?string $actingAs = null): array
    {
        $data = \Synthigy\Synthigy::query(_SRC_MOVIE_LIST, $params, actingAs: $actingAs);
        return is_array($data) ? array_values($data) : [];
    }

    /**
     * @param array{xid: string} $params
     * @return array{xid: string, title: string|null, release_year: int|null, movie_ratings?: list<array{xid: string, value: float, review: string|null, created_by?: array{xid: string, name: string|null}}>, genres?: list<array{xid: string, name: string|null}>, actors?: list<array{xid: string, name: string|null, birth_year: int|null}>}|null
     */
    public static function detail(array $params = [], ?string $actingAs = null): ?array
    {
        $data = \Synthigy\Synthigy::query(_SRC_MOVIE_DETAIL, $params, actingAs: $actingAs);
        return is_array($data) ? $data : null;
    }

    /**
     * @param array{since?: int, q?: string} $params
     * @return list<array{total: int}>
     */
    public static function count(array $params = [], ?string $actingAs = null): array
    {
        $data = \Synthigy\Synthigy::sqlTemplate(_SRC_MOVIE_COUNT, $params, actingAs: $actingAs);
        return is_array($data) ? array_values($data) : [];
    }
}

final class Batches
{
    /**
     * Batch: list + stats — ONE wire request; results keyed by member
     * name. A failed member's value is a SynthigyError instance, never
     * a raised batch-wide error.
     *
     * @param array<string,mixed> $params forwarded to every member's query verbatim (v1: no per-member param merge/dedupe)
     * @return array<string, mixed>
     */
    public static function overview(array $params = [], ?string $actingAs = null): array
    {
        $operations = [
            \Synthigy\opQuery(_SRC_MOVIE_LIST, $params),
            \Synthigy\opSqlTemplate(_SRC_DASHBOARD_STATS, $params),
        ];
        $results = \Synthigy\Synthigy::exec($operations, actingAs: $actingAs);
        return [
            'list' => \Synthigy\batchResult($results[0] ?? [], 'search'),
            'stats' => \Synthigy\batchResult($results[1] ?? [], 'sql-template'),
        ];
    }
}

/**
 * @phpstan-type MovieInput array{xid?: string, release_year?: int|null, title?: string|null, genres?: list<(array{xid: string}|MovieGenreInput)>, movie_ratings?: list<(array{xid: string}|UserRatingInput)>, actors?: list<(array{xid: string}|MovieActorInput)>}
 * @phpstan-type MovieActorInput array{xid?: string, name?: string|null, nationality?: string|null, birth_year?: int|null, movies?: list<(array{xid: string}|MovieInput)>}
 * @phpstan-type MovieGenreInput array{xid?: string, name?: string|null, movies?: list<(array{xid: string}|MovieInput)>}
 * @phpstan-type UserInput array{xid?: string, priority?: int|null, settings?: mixed|null, name?: string|null, avatar?: mixed|null, type?: 'PERSON'|'SERVICE'|'ROBOT'|null, modified_on?: string|null, password?: string|null, active?: bool|null, created_on?: string|null, notification_preferences?: list<array<string, mixed>>, owner?: (array{xid: string}|UserInput), user_profile?: array<string, mixed>, loggers?: list<array<string, mixed>>, person_info?: array<string, mixed>, company_section?: array<string, mixed>, can_read_folder?: list<array<string, mixed>>, sessions?: list<array<string, mixed>>, notifications?: list<array<string, mixed>>, chat_groups?: list<array<string, mixed>>, external_identities?: list<array<string, mixed>>, created_by?: (array{xid: string}|UserInput), authorized_client?: array<string, mixed>, approval_records?: list<array<string, mixed>>, robot_repo?: array<string, mixed>, approvals?: list<array<string, mixed>>, public_profile?: array<string, mixed>, installations?: list<array<string, mixed>>, owned_datasets?: list<array<string, mixed>>, can_write_folder?: list<array<string, mixed>>, quick_filters?: list<array<string, mixed>>, owner_group?: array<string, mixed>, projects?: list<array<string, mixed>>, modified_by?: (array{xid: string}|UserInput), can_delete_folder?: list<array<string, mixed>>, roles?: list<array<string, mixed>>, groups?: list<array<string, mixed>>}
 * @phpstan-type UserRatingInput array{xid?: string, value: float, review?: string|null, modified_on?: string|null, created_on?: string|null, modified_by?: (array{xid: string}|UserInput), user?: array<string, mixed>, movie?: (array{xid: string}|MovieInput), created_by?: (array{xid: string}|UserInput)}
 */
final class Writes
{
    /**
     * Upsert one movie record — REPLACES relation link-sets.
     *
     * Silent by default: answers ['count' => n]. Pass $returning for the
     * written record, or mint the id up front with \Synthigy\newXid().
     *
     * @param MovieInput $data
     * @return array<string, mixed>
     */
    public static function syncMovie(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::sync('movie', $data, $actingAs, null, $returning);
    }

    /**
     * Additive write to one movie record — relation links are ADDED, never removed.
     * Same $returning contract as syncMovie.
     *
     * @param MovieInput $data
     * @return array<string, mixed>
     */
    public static function stackMovie(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::stack('movie', $data, $actingAs, null, $returning);
    }

    /** Soft-delete one movie record by xid. */
    public static function deleteMovie(string $xid, ?string $actingAs = null): bool
    {
        return \Synthigy\Synthigy::delete('movie', ['xid' => $xid], $actingAs);
    }

    /**
     * Upsert one movie_actor record — REPLACES relation link-sets.
     *
     * Silent by default: answers ['count' => n]. Pass $returning for the
     * written record, or mint the id up front with \Synthigy\newXid().
     *
     * @param MovieActorInput $data
     * @return array<string, mixed>
     */
    public static function syncMovieActor(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::sync('movie_actor', $data, $actingAs, null, $returning);
    }

    /**
     * Additive write to one movie_actor record — relation links are ADDED, never removed.
     * Same $returning contract as syncMovieActor.
     *
     * @param MovieActorInput $data
     * @return array<string, mixed>
     */
    public static function stackMovieActor(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::stack('movie_actor', $data, $actingAs, null, $returning);
    }

    /** Soft-delete one movie_actor record by xid. */
    public static function deleteMovieActor(string $xid, ?string $actingAs = null): bool
    {
        return \Synthigy\Synthigy::delete('movie_actor', ['xid' => $xid], $actingAs);
    }

    /**
     * Upsert one movie_genre record — REPLACES relation link-sets.
     *
     * Silent by default: answers ['count' => n]. Pass $returning for the
     * written record, or mint the id up front with \Synthigy\newXid().
     *
     * @param MovieGenreInput $data
     * @return array<string, mixed>
     */
    public static function syncMovieGenre(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::sync('movie_genre', $data, $actingAs, null, $returning);
    }

    /**
     * Additive write to one movie_genre record — relation links are ADDED, never removed.
     * Same $returning contract as syncMovieGenre.
     *
     * @param MovieGenreInput $data
     * @return array<string, mixed>
     */
    public static function stackMovieGenre(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::stack('movie_genre', $data, $actingAs, null, $returning);
    }

    /** Soft-delete one movie_genre record by xid. */
    public static function deleteMovieGenre(string $xid, ?string $actingAs = null): bool
    {
        return \Synthigy\Synthigy::delete('movie_genre', ['xid' => $xid], $actingAs);
    }

    /**
     * Upsert one user record — REPLACES relation link-sets.
     *
     * Silent by default: answers ['count' => n]. Pass $returning for the
     * written record, or mint the id up front with \Synthigy\newXid().
     *
     * @param UserInput $data
     * @return array<string, mixed>
     */
    public static function syncUser(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::sync('user', $data, $actingAs, null, $returning);
    }

    /**
     * Additive write to one user record — relation links are ADDED, never removed.
     * Same $returning contract as syncUser.
     *
     * @param UserInput $data
     * @return array<string, mixed>
     */
    public static function stackUser(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::stack('user', $data, $actingAs, null, $returning);
    }

    /** Soft-delete one user record by xid. */
    public static function deleteUser(string $xid, ?string $actingAs = null): bool
    {
        return \Synthigy\Synthigy::delete('user', ['xid' => $xid], $actingAs);
    }

    /**
     * Upsert one user_rating record — REPLACES relation link-sets.
     *
     * Silent by default: answers ['count' => n]. Pass $returning for the
     * written record, or mint the id up front with \Synthigy\newXid().
     *
     * @param UserRatingInput $data
     * @return array<string, mixed>
     */
    public static function syncUserRating(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::sync('user_rating', $data, $actingAs, null, $returning);
    }

    /**
     * Additive write to one user_rating record — relation links are ADDED, never removed.
     * Same $returning contract as syncUserRating.
     *
     * @param UserRatingInput $data
     * @return array<string, mixed>
     */
    public static function stackUserRating(array $data, ?string $actingAs = null, bool $returning = false): array
    {
        return \Synthigy\Synthigy::stack('user_rating', $data, $actingAs, null, $returning);
    }

    /** Soft-delete one user_rating record by xid. */
    public static function deleteUserRating(string $xid, ?string $actingAs = null): bool
    {
        return \Synthigy\Synthigy::delete('user_rating', ['xid' => $xid], $actingAs);
    }
}
